name: emarsys-sdk.js CI - build and publish

on: [push]

env:
  NODE_VERSION: '12.13'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies and test
      run: |
        npm ci
        npm run test
    - name: build 
      run: npm run build
    - name: publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish
