name: miza-kinesis - npm-publish

on:
  release:
    types: [created]

env:
  NODE_VERSION: '12.13'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies and test
      run: |
        npm ci
        npm run lint
        npm run test
    - name: Publish to npm
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
